schema_version: 1

context:
  version: "0.1.6"

package:
  name: sgp4jax
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sgp4jax/sgp4jax-${{ version }}.tar.gz
  sha256: 50fd31c167a4263d2e715f6b045acf682017fb785f0aeef0c253335854b52c9a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - jax >=0.4.0
    - jaxlib >=0.4.0
    - numpy >=1.22

tests:
  - python:
      imports:
        - sgp4jax
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: JAX-compatible SGP4 satellite propagation
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - THIRD_PARTY_NOTICES
  homepage: https://pypi.org/project/sgp4jax/

extra:
  recipe-maintainers:
    - chrisfinlay
